### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by mupp675** [graemeniedermayer/stable-diffusion-webui-normalmap-script#6]
I tried to install this today with the latest WebUi following your install instructions but when launched it gives this error.

Error loading script: normalmap.py
Traceback (most recent call last):
  File "D:\spooky\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\spooky\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\spooky\stable-diffusion-webui\extensions\stable-diffusion-webui-normalmap-script\scripts\normalmap.py", line 31, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "D:\spooky\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "D:\spooky\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 21, in <module>
    from .backbones.next_vit import (
  File "D:\spooky\stable-diffusion-webui\repositories\midas\midas\backbones\next_vit.py", line 8, in <module>
    file = open("./externals/Next_ViT/classification/nextvit.py", "r")
FileNotFoundError: [Errno 2] No such file or directory: './externals/Next_ViT/classification/nextvit.py'

**Comment by graemeniedermayer** [comment]
It looks like midas was recently updated breaking some things. I'll should be able to fix in the next few days.

If you need it today there's some fixes suggested in

https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/55

**Comment by graemeniedermayer** [comment]
Okay it should be working now! With some better more advanced depth models!

**Comment by mupp675** [comment]
Yes, now it works. Thanks.
