### ISSUE TITLE
Loading Error Normalmap.py

### ISSUE THREAD

**Issue by FuatW** [graemeniedermayer/stable-diffusion-webui-normalmap-script#9]
*** Error loading script: normalmap.py
    Traceback (most recent call last):
      File "C:\Users\Fuat\Desktop\Stable Diffusion\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Fuat\Desktop\Stable Diffusion\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Fuat\Desktop\Stable Diffusion\sd.webui\webui\extensions\stable-diffusion-webui-normalmap-script\scripts\normalmap.py", line 9, in <module>
        from modules.shared import opts, cmd_opts, state, Options
    ImportError: cannot import name 'Options' from 'modules.shared' (C:\Users\Fuat\Desktop\Stable Diffusion\sd.webui\webui\modules\shared.py)

---

**Comment by graemeniedermayer** [comment]
Thanks! I removed ` 'Options' from 'modules.shared' ` so hopefully it's working for you now!

If you have any more trouble let me know.
